# permissions for end users to edit accountnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accountnode-editor-role
rules:
- apiGroups:
  - infra.kloudlite.io
  resources:
  - accountnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.kloudlite.io
  resources:
  - accountnodes/status
  verbs:
  - get
