# permissions for end users to edit cloudproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudprovider-editor-role
rules:
- apiGroups:
  - infra.kloudlite.io
  resources:
  - cloudproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.kloudlite.io
  resources:
  - cloudproviders/status
  verbs:
  - get
