# permissions for end users to view accountnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accountnode-viewer-role
rules:
- apiGroups:
  - infra.kloudlite.io
  resources:
  - accountnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.kloudlite.io
  resources:
  - accountnodes/status
  verbs:
  - get
