# permissions for end users to view accountproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accountprovider-viewer-role
rules:
- apiGroups:
  - infra.kloudlite.io
  resources:
  - accountproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.kloudlite.io
  resources:
  - accountproviders/status
  verbs:
  - get
