# permissions for end users to view regions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: region-viewer-role
rules:
- apiGroups:
  - management.kloudlite.io
  resources:
  - regions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.kloudlite.io
  resources:
  - regions/status
  verbs:
  - get
