---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - infra.kloudlite.io
  resources:
  - accountnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.kloudlite.io
  resources:
  - accountnodes/finalizers
  verbs:
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - accountnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - cloudproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.kloudlite.io
  resources:
  - cloudproviders/finalizers
  verbs:
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - cloudproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - edges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.kloudlite.io
  resources:
  - edges/finalizers
  verbs:
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - edges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - nodepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.kloudlite.io
  resources:
  - nodepools/finalizers
  verbs:
  - update
- apiGroups:
  - infra.kloudlite.io
  resources:
  - nodepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - management.kloudlite.io
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.kloudlite.io
  resources:
  - accounts/finalizers
  verbs:
  - update
- apiGroups:
  - management.kloudlite.io
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - management.kloudlite.io
  resources:
  - devices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.kloudlite.io
  resources:
  - devices/finalizers
  verbs:
  - update
- apiGroups:
  - management.kloudlite.io
  resources:
  - devices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - management.kloudlite.io
  resources:
  - domains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.kloudlite.io
  resources:
  - domains/finalizers
  verbs:
  - update
- apiGroups:
  - management.kloudlite.io
  resources:
  - domains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - management.kloudlite.io
  resources:
  - regions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.kloudlite.io
  resources:
  - regions/finalizers
  verbs:
  - update
- apiGroups:
  - management.kloudlite.io
  resources:
  - regions/status
  verbs:
  - get
  - patch
  - update
