apiVersion: management.kloudlite.io/v1
kind: Device
metadata:
  name: device-plax
spec:
  activeRegion: master
  accountId: sample-account
  offset: 2
  ports:
    - port: 3000
    - port: 3001

---

apiVersion: management.kloudlite.io/v1
kind: Device
metadata:
  name: device-plax2
spec:
  activeRegion: master
  accountId: sample-account
  offset: 3
  ports:
    - port: 3000
    - port: 3001


  # TODO(user): Add fields here
