# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/management.kloudlite.io_accounts.yaml
- bases/management.kloudlite.io_clusters.yaml
- bases/management.kloudlite.io_devices.yaml
- bases/management.kloudlite.io_domains.yaml
- bases/management.kloudlite.io_regions.yaml
#+kubebuilder:scaffold:crdkustomizeresource
